### ISSUE TITLE
Virtual filesystem

### ISSUE THREAD

**Issue by grimnight** [phillbush/xfiles#30]
Being able to have a virtual filesystem view created from list of paths from stdin or from a script would have uses. It would make it possible to create a trash bin, with [#29]. Or create a virtual view from [Export File Format] used by [ncdu]. If implemented, it maybe necessary to be able to set a custom xfilesctl script.

I do not know if this is in line with what you have been planning for xfiles, but I thought i'd atleast ask.

[#29]: https://github.com/phillbush/xfiles/issues/29
[Export File Format]: https://dev.yorhel.nl/ncdu/jsonfmt
[ncdu]: https://code.blicky.net/yorhel/ncdu

**Comment by phillbush** [comment]
That will not be implemented into XFiles.

First because it would break for `xfilesctl` the assumption that you're dealing with actual files on the file system.

Second because you can already use virtual filesystems with [FUSE](https://en.wikipedia.org/wiki/Filesystem_in_Userspace), as you can see in this video where I create a virtual filesystem `~/union` containing the union of the directories `~/yellow` and `~/blue`, and the virtual filesystem `~/overboard` containing the data in `~/overboard.zip`.

https://user-images.githubusercontent.com/63266536/213600228-d9b4cc33-d625-458b-85ea-70f0ff249a9e.mp4

NOTE: OpenBSD (the system I use) requires the FUSE to be mounted as root (with `doas`) that is not needed on Linux (you can do that as a regular user). Mounting with `-o allow_other` may also be not needed, idk.
