### ISSUE TITLE
Exec file and symlinc dir icons are no longer shown.

### ISSUE THREAD

**Issue by tdukv** [phillbush/xfiles#35]
The icons for executable file and symlink directory are not loaded anymore, instead the default file/dir icons are shown.

**Comment by phillbush** [comment]
Hi,

Previously, the glob-pattern to icon mapping was done by editing the source code, that allowed more customization at the price of a complex syntax (and the need to recompile).

Now, all configuration is done via X resources. Settings are processed at invocation, and re-processed when the resource database changes.  Configuration is now parsed from a string, rather than read directly from the memory, so a simpler syntax is more desirable.  In this case, i opted to use a style similar to `$LS_COLORS` for the `fileIcons` resource:

```
PATTERN_1=ICON_1:PATTERN_2=ICON_2:...:PATTERN_N=ICON_N
```

(The colon can be replaced with a newline).

I don't know how can i add the file metadata (directory, link, executable, etc) while still keeping it simple and compatible to what it looks like now. If you have any suggestion for a new syntax, i'm happy to hear it.

**Comment by phillbush** [comment]
Hi, I have implemented a (kinda hacky) way to add metadata to icon patterns: append a character (like `|` and `@`) indicating the file type to the pattern.  The bad thing is that now patterns cannot end in `|` or `@` (but why one would name a file with `|` or `@`, and at the end of the file name?).

An entry on `fileIcons` like `PATTERN/=ICON` is interpreted as a directory, `PATTERN@=ICON` is a link, `PATTERN|=ICON` is a fifo (aka named pipe), etc. It is not documented yet, i still need to include such configuration in the manual.

Icons for executable files and symbolic links are set by default, so no configuration is necessary.
I have also added an icon for broken symlinks, which is also set by default.
