### ISSUE TITLE
using mime types instead of extensions

### ISSUE THREAD

**Issue by apprehensions** [phillbush/xfiles#37]
in my eyes, mime types have existed simply to remove the need for having to add every single extension to every single program, when needed; instead of using a single database that can simply have one 'mime' type for various extensions.

for xfiles, this can save some effort in the configuration file, so the user doesnt have to know which extensions and have to go to the hassle of re-configuring and re-compiling. i had faced this earlier today with .webp files and .opus files.

it seems both linux and openbsd support magic(4), via `magic.h`.

**Comment by phillbush** [comment]
I have already work with libmagic in another project of mine ([a file opener/xdg-open replacement](https://github.com/phillbush/plumb)), which not only adds mimetypes but also uses regexp for matching against them, so I have familiarity with it and know that it is doable.

The problems are:

- **It breaks compatibility:** Configuration now is done at runtime with a simple `LS_COLORS`-like syntax. Adding the option to use mimetipes without breaking existent configurations is a challenge. And fully replacing filename+globbing with plain mimetypes (or mimetypes+regex) will break existent configuration. And breaking configuration is now a problem after 1.0 (it was less so before I adopted versioning) and after being packaged in a OS repository.
- **It adds dependency:** (I have OpenBSD in mind while I say that, because that is the system I use). XFiles can be compiled and works on a base installation with only the X server and X libraries installed. Adding libmagic as a dependency drops XFiles' availability on those systems to a small degree.
- **It can be hard (for me):** Other than using libmagic to deal with the magic database, I could use the plain magic db, but I have never used it. I can study it and see how feasible (and how easy) using the plain magic db can be. I also do not know how available is the magic database on different UNIXes. I know that the database is closely related to the `file(1)` command, which is available in most UNIX, but not standardized nor required.
- **It requires read access to the files in a directory.** (In order to check the content).
- **It requires to read all the files in a directory!** For plumb (and other file openers) that is not a problem: you're dealing with a single file which you probably have read access and will open it anyway. But consider doing that on a directory with lots of files! I know that for most files you only need to read a few bytes at the beginning of the file to know its mimetype. But do that a hundred of times. This may not be a problem, however if icons are loaded asynchronously on a separate thread (just like how thumbnails do). But doing that will add another thread to XFiles, and would require to use a placeholder icon while the actual icon has not be inferred from the mimetype.

I will study implementing that later, both via libmagic and manually parsing the database, and see how that can be done.

**Comment by apprehensions** [comment]
fixed due to moving thumbnail handling to another program
