### ISSUE TITLE
feature request: icons should be installed and easily picked up by xfiles

### ISSUE THREAD

**Issue by wael444** [phillbush/xfiles#7]
for example:
```
export FILE_ICONS="
d:..=$ICONPATH/64x64/folder-up.xpm
d:$HOME=$ICONPATH/64x64/folder-home.xpm
d:*=$ICONPATH/64x64/folder.xpm
-:*.zip|*.tar.*|*.tar|*.gz|*.rar=$ICONPATH/64x64/file-archive.xpm
-:*.mp4|*.webm|*.mkv|*.mov=$ICONPATH/64x64/file-video.xpm
-:*.xpm|*.xbm|*.png|*.jpg|*.ppm|*.jpeg|*.gif=$ICONPATH/64x64/file-image.xpm
-:*.mp[23]|*.ogg|*.opus|*.flac=$ICONPATH/64x64/file-music.xpm
-:*.pdf|*.epub|*.txt|*.ps|*.eps|*.djvu=$ICONPATH/64x64/file-text.xpm
*=$ICONPATH/64x64/file.xpm
"
```
`ICONPATH` is unknown. (hopefully) if icons are going to be installed in `PREFIX/share/xfiles/icons`; controlled by Makefile; could easily be picked up by xfiles for example like
```
d:..=folder-up
```

**Comment by wael444** [comment]
or controlled by a new variable such as `XFILES_ICONPATH`

**Comment by wael444** [comment]
or automatically assign icons to folders or files matching names via some variable idk.

**Comment by phillbush** [comment]
I do not want to install lots of stuff into users' file system, especially things that may be added and removed as development goes on, like icons.

For example, if I deprecate an icon, it would not be removed by `make uninstall` because `make` would not know about it (for it would not be listed on the Makefile).

For the sake of making uninstalling work, Makefile must only track files that are not likely to be added and removed during development; the binary and the manual are currently the only ones of such constant files.

In the end, requiring manual configuration for the icons may be good: the user can decide which icons to use and even modify them with Gimp.

For example, there's an icon I have drawn for myself that I use for my meme folder (`./icons/folder-meme.xpm`). I have included it here just because I have no other place to share it. There's no need to require users to install it if they're likely not going to need it.

That leads to a question: Should I move the icons  I have drawn into a separate repository, and only keep here the ones necessary for compilation: `./icons/file.xpm` and `./icons/folder.xpm`? (Also, should I use other icons as default? I do not have much art skills, and those icons are not as nice as, say, haiku's ones).

PS: You can open `.xpm` icons with [feh](https://feh.finalrewind.org/).

**Comment by wael444** [comment]
seninha, this is a file manager project. who doesn't expect configurable icons to come with it? especially if it's gui. personally i use every single icon provided in xfiles:
![image](https://user-images.githubusercontent.com/47404953/211132614-963dda55-bdd1-4718-8379-7835068488f2.png)
i would at LEAST suggest to have a `XFILES_ICONSPATH` and to have a format like `d:bin=folder-meme`.

**Comment by phillbush** [comment]
I think I'm going to deprecate `XFILES_ICONSPATH` and just load the icons at compile time, so there will be no need for installing icons or set an environment variable: the icons will be specified in the code itself.  
I'll create a `config.h` and list the icons there.

I want to do this because there are already icons being loaded at compile time: `file.xpm` and `folder.xpm`.  
If you have not set `XFILES_ICONSPATH`, it will still use those compile-time icons.  
So why have some icons compiled into the binary, and others loaded at run time?

**Comment by wael444** [comment]
> the icons will be specified in the code itself.
I'll create a config.h and list the icons there.

paths of the icons? or the icons for the names of folders or whatever? are you gonna do something similar to `d:bin=folder-meme` ?

**Comment by phillbush** [comment]
No more need for icons to be installed. They are already included in the program at compile time (resulting on a slightly larger binary).

After defining the file patterns, associating them with icons require filling a table like this:

```
char **icons[][2] = {
․       { file_makefile,   file_gear_xpm,       },
․       { file_image,      file_image_xpm,      },
․       { file_svg,        file_image_xpm,      },
․       { file_readme,     file_info_xpm,       },
․       { folder_bin,      folder_apps_xpm,     },
․       { folder_home,     folder_home_xpm,     },
․       { folder_meme,     folder_meme_xpm,     },
// ...
․       { folder,          folder_xpm,          },
․       { NULL,            file_xpm,            },
};
```
